# Generated by Django 5.0.2 on 2024-03-22 00:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newsAgency', '0003_remove_author_name_remove_author_password_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newsstory',
            name='details',
            field=models.CharField(max_length=128),
        ),
    ]
